workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 90
    environment:
      vars:
        FLUTTER_VERSION: "3.24.5"
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --android-skip-build-dependency-validation
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
